#!/bin/ksh
#
# This repository has local copies of the iPXE binaries we provide to CNs that
# use BIOS PXE instead of booting iPXE from a local USB key.
#
# This script updates to the latest binaries from the ipxe tarball.
#
# Copyright (c) 2018, Joyent, Inc.

IPXEFILES="./boot/undionly.kpxe ./boot/snponly.efi"


set -o errexit
set -o pipefail

tdir=
dir="$(dirname $(whence $0))/.."
cd "${dir}"

function fatal {
	printf "ERROR: %s\n" "$*" >&2
	if [[ -n "${tdir}" && -d "${tdir}" ]]; then
		# Clean up temporary directory
		rm -rf "${tdir}"
	fi
	exit 1
}

branch=${1:-master}

if ! mdir="$(mget -q /Joyent_Dev/public/builds/ipxe/$branch-latest)"; then
	fatal "could not locate latest ipxe build directory in Manta"
fi

printf "%15s: %s\n" "Manta Dir" "${mdir}" >&2

if ! mfile="$(mfind -t o -n "^ipxe-$branch-.*.tar.gz$" "${mdir}")"; then
	fatal "could not locate latest ipxe build tarball in Manta"
fi

printf "%15s: %s\n" "Manta File" "${mfile}" >&2

if ! tdir="$(/usr/bin/mktemp -d)"; then
	fatal "could not make temporary directory"
fi

printf "%15s: %s\n" "Temp Dir" "${tdir}" >&2
cd "${tdir}"

if ! mget -o ipxe.tar.gz "${mfile}"; then
	fatal "could not download ${mfile}"
fi

if ! tar xvzf ipxe.tar.gz ${IPXEFILES}; then
	fatal "could not extract iPXE binaries from tarball"
fi

mv ${IPXEFILES} ${dir}/tftpboot
cd /
rm -rf "${tdir}"

printf "ok\n" >&2
